### ISSUE TITLE
Teku client lost all peers and no new peers until restart

### ISSUE THREAD

**Issue by kirillp** [Consensys-Incorporated/teku#4377]
### Description
Im trying to stake with teku, latest version teku-21.9.1

### Acceptance Criteria
It works

### Steps to Reproduce (Bug)
I run teku as expected 

```
title "teku pyrmont eth-goerli.alchemyapi"
set eth_svc=https://eth-goerli.alchemyapi.io/v2/secretSessionKey
set JAVA_HOME=C:\Java\openjdk-16.0.1
bin/teku.bat --network=pyrmont --eth1-endpoint=%eth_svc% --data-path test-data --p2p-nat-method=UPNP

```

**Expected behavior:** [What you expect to happen]
I expect network to sync. It does not.
Other clients like Prysm and Lighthouse works perfectly

**Actual behavior:** [What actually happens]
Peer count goes down to zero and stop sync.

**Frequency:** [What percentage of the time does it occur?]
100%

### Versions (Add all that apply)
* Software version: [`teku --version`]
  teku/v21.9.1/windows-x86_64/oracle_openjdk-java-16

* Java version: [`java -version`]
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

* OS Name & Version: [`cat /etc/*release`]
 windows

**Comment by kirillp** [comment]
this is fill client log
https://gist.github.com/kirillp/35cbbc0007f9df3209f36dfd0365f21e

**Comment by kirillp** [comment]
"--p2p-nat-method=UPNP" was my experiments, with default value it does not work also

**Comment by chrishobcroft** [comment]
Is anyone still running on `pyrmont`?

Does it work with `prater` network?

**Comment by ajsutton** [comment]
Thanks for logging this.  The log you've included is only the console output.  Teku sends most of it's log information to a log file by default which is in `test-data\logs\teku.log` if you could give us that log it would be very useful in helping to track down what's going wrong here.

**Comment by kirillp** [comment]
Hello, I have gather some logs for you
[teku_logs.zip](https://github.com/ConsenSys/teku/files/7184659/teku_logs.zip)
 this is 2 sessions, both failed with 0 peers

I can start another one if you need

**Comment by ajsutton** [comment]
Thanks.  These logs are showing the error quite clearly:
```
Caused by: java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: C:\eth2\teku\test-data\beacon\db\1892432.sst: Could not create random access file.
```

There is either a permissions problem that is causing Teku to be unable to create the file or perhaps the disk is out of disk space.  Unfortunately Windows isn't giving us much information about what's going wrong but it's this inability to write to the database that causing the problems.

**Comment by kirillp** [comment]
I saw this but other clients dont have any issues, also this folder dont have any issues and free space is 350+GB
My PC dont have any non-standart antivirus software, clean windows installation.
If other eth2 clients (Prysm, Lighthouse) do not have any disk issues I think this is a problem of Teku implementation.

Also I tried to create the file manually, and I can do it.

**Comment by kirillp** [comment]
this, unfortunately, block using Teku for me

**Comment by kirillp** [comment]
I see this again in the log 
2021-09-17 14:21:45.804+03:00 | forkchoice-async-0 | ERROR | BlockImporter | Internal error while importing block: 216270..4a93 (2181408)
java.util.concurrent.CompletionException: java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: C:\eth2\teku\test-data\beacon\db\1911619.sst: Could not create random access file.

same time I can create that file without any issues (teku is still running)

`echo Could not create random access file. > C:\eth2\teku\test-data\beacon\db\1911619.sst`

and it exists:

`ls C:\eth2\teku\test-data\beacon\db\1911619.sst`

```
    Directory: C:\eth2\teku\test-data\beacon\db
-a----         17-Sep-21     14:45             39 1911619.sst
```

**Comment by kirillp** [comment]
It was my experiment with data size, Teku is leading, it consumes less disk space but have file IO issues

Teku uses 22g for pyrmont network
Prysm uses 35g for pyrmont network
Lighthouse is still syncing

**Comment by benjaminion** [comment]
Hi, I am running Teku on Windows without problems, and just tried v21.9.1.

As a sanity check, could you try just starting teku with no options. It will then try to make a new database somewhere like %USER%\AppData\Local\teku\beacon. If this works ok, then there is most likely a permissions issue somewhere.

**Comment by kirillp** [comment]
I don't see how can this be permissions issues, I have the only user, I created the folder.

Starting from the scratch may hide the problem. Do we want this? 
It is easy reproduceble. 
Currently I see blocking IO issue with Teku.

**Comment by benjaminion** [comment]
Just trying to narrow down the issue. I completely agree that if there is a problem then we should fix it. But we don't know the root cause of the problem yet and need to track it down somehow.

> It is easy reproduceble.

I am unable to reproduce this. Teku is running fine on Windows here. My data directory is `E:\teku\data\beacon`.

**Comment by kirillp** [comment]
I will reinit the node, i`ll take the fast scenario https://www.youtube.com/watch?v=ce9uVRl23zI

**Comment by kirillp** [comment]
Is there a way I can check DB integrity ? Is there some kind of _chkdsk_ equivalent?

**Comment by kirillp** [comment]
I have restarted from the latest state and it still does not valiate. 
Despite it render that 
> 17:38:56.069 INFO  - Validator   *** Published attestation        Count: 1, Slot: 2182394, Root: f2adbb..b522
the attestation is missed for slot 2182394  https://pyrmont.beaconcha.in/validator/127106#attestations

**Comment by kirillp** [comment]
starting Teku form scratch using —initial-state and 
I dont see any problems. 

This seems to be DB corruption issues.

**Comment by kirillp** [comment]
I filed a new issue regarding this: https://github.com/ConsenSys/teku/issues/4393
